### PR TITLE
Pr/pylint issues

### PR DESCRIPTION
**Pull request by rienafairefr**
Small changes, e.g. in method signatures in order to avoid adding pylint disable if not needed

### CODE REVIEW

**Comment by aabadie** [comment]
It's unclear to me why those changes are required. Can you explain a bit more ?

**Comment by aabadie** [comment]
78f6b27  is useless IMHO

**Comment by rienafairefr** [comment]
pylint now has some warnings as errors. One way to deal with the error is to silence it (disable the check for that specific line like [#43](https://github.com/iot-lab/iot-lab-gateway/pull/43) the other way is to modify the code so it doesn't trigger the check

78f6b27 is keeping things the same, if it's a string argument you format it like a string argument, like it was before.

You can disregard this PR if you want, just nitpicks

**Comment by aabadie** [comment]
> One way to deal with the error is to silence it (disable the check for that specific line like #43 the other way is to modify the code so it doesn't trigger the check

This is an obvious assertion. The question is more is a code change really required ? I don't think so. The changes proposed by 70b9a14  and 8758190 may introduce side effects that I want to avoid if no valid reason is given.

> 78f6b27 is keeping things the same, if it's a string argument you format it like a string argument, like it was before.

`format` does that for us under the hood and no need to be explicit in this case.

**Pull request closed without merging**
